title: Z.R. Wagner
author: Z.R. Wagner
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Z.R. Wagner.
baseurl: "/"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: zrwagner
# twitter_username: 
# instagram_username: 

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
